import type { Metadata } from "next";
import "../style/editor.css"
import "./globals.css";
<<<<<<< HEAD
import "../style/editor-theme.css"
=======
import "../style/editor.css"
import "../style/editor-theme.css"

import { EditorStateProvider } from "./context/EditorStateContext";
>>>>>>> 9b910c7 ([Editor] ul feature added)

import { EditorStateProvider } from "./context/EditorStateContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body>
=======
      <body className={inter.className}>
>>>>>>> 9b910c7 ([Editor] ul feature added)
        <EditorStateProvider>
          {children}
        </EditorStateProvider>
      </body>
    </html>
  );
}
